version: "3.8"
services:
  firefly:
    image: firefly
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    environment:
      - PORT=8080
